<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="DESKTOP-GH8JCFT"><DocLocation><![CDATA[C:\Users\Admin\Desktop\Capgemini Study Material\Keyboard_driven_framework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res21]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:32]]></Time>
<TimeTick>1648536632</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:32]]></Time>
<TimeTick>1648536632</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:34]]></Time>
<TimeTick>1648536634</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:34]]></Time>
<TimeTick>1648536634</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:34]]></Time>
<TimeTick>1648536634</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="18" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:35]]></Time>
<TimeTick>1648536635</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:38]]></Time>
<TimeTick>1648536638</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:48]]></Time>
<TimeTick>1648536648</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:48]]></Time>
<TimeTick>1648536648</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="26" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="25" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:50]]></Time>
<TimeTick>1648536650</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:50]]></Time>
<TimeTick>1648536650</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:51]]></Time>
<TimeTick>1648536651</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:54]]></Time>
<TimeTick>1648536654</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:54]]></Time>
<TimeTick>1648536654</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:55]]></Time>
<TimeTick>1648536655</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:56]]></Time>
<TimeTick>1648536656</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:20:59]]></Time>
<TimeTick>1648536659</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:07]]></Time>
<TimeTick>1648536667</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:07]]></Time>
<TimeTick>1648536667</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="49" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="48" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:08]]></Time>
<TimeTick>1648536668</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:08]]></Time>
<TimeTick>1648536668</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:09]]></Time>
<TimeTick>1648536669</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:12]]></Time>
<TimeTick>1648536672</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:12]]></Time>
<TimeTick>1648536672</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:12]]></Time>
<TimeTick>1648536672</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:13]]></Time>
<TimeTick>1648536673</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[numOfTicketsCombo.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:16]]></Time>
<TimeTick>1648536676</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" >
<Disp><![CDATA[numOfTicketsCombo.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[updateBtn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:17]]></Time>
<TimeTick>1648536677</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="70" >
<Disp><![CDATA[updateBtn.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/29/2022 - 12:21:20]]></Time>
<TimeTick>1648536680</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="72" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="15" status="Passed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/29/2022 - 12:20:24" eTime="3/29/2022 - 12:21:22" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T33">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="3/29/2022 - 12:21:22" eTime="3/29/2022 - 12:21:22" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="74" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T34">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="3/29/2022 - 12:21:22" eTime="3/29/2022 - 12:21:23" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="76" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="3/29/2022 - 12:20:20" eTime="3/29/2022 - 12:21:23" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>